# Generated by Django 3.2.12 on 2022-02-05 17:23

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('subjects', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('duration', models.IntegerField(default=0)),
                ('limit', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('to_do', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('compulsory', models.BooleanField(default=False)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('limit', models.IntegerField(default=0)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.examination')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('to_do', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('unit_subtopic', models.IntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('to_do', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(blank=True, max_length=30, null=True)),
                ('question_text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('a', ckeditor_uploader.fields.RichTextUploadingField()),
                ('b', ckeditor_uploader.fields.RichTextUploadingField()),
                ('c', ckeditor_uploader.fields.RichTextUploadingField()),
                ('d', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('e', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('ans', models.CharField(max_length=1)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank.subject')),
                ('subtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.subtopic')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.topic')),
            ],
        ),
    ]
