# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-13 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='batch',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
