# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-01-21 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_question_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='batch',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
