# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2020-02-14 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_auto_20190211_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='group_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
