# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2020-02-14 20:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mngr', '0014_auto_20200203_2239'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0005_question_group_name'),
        ('userprofile', '0007_auto_20200214_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('sex', models.CharField(choices=[('F', 'female'), ('M', 'male')], max_length=1)),
                ('phone', models.CharField(max_length=13)),
                ('issued_by', models.CharField(max_length=200)),
                ('regnum', models.CharField(max_length=10, verbose_name='Serial')),
                ('online', models.BooleanField(default=False)),
                ('regdate', models.DateTimeField(auto_now_add=True)),
                ('exam_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userprofile.ExamCenter')),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank.Examination')),
                ('feedback', models.ForeignKey(blank=True, help_text='How did you hear about this mock?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mngr.Advert')),
                ('subject', models.ManyToManyField(to='bank.Subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CenterCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=6)),
                ('srn', models.CharField(max_length=8, unique=True)),
                ('generated', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('used', models.BooleanField(default=False)),
                ('user', models.CharField(blank=True, max_length=150, null=True)),
                ('time_used', models.DateTimeField(blank=True, null=True)),
                ('issued', models.BooleanField(default=False)),
                ('buyer', models.CharField(blank=True, max_length=200, null=True)),
                ('set_name', models.CharField(blank=True, max_length=200, null=True)),
                ('alert', models.BooleanField(default=False)),
                ('alert_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CenterResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('started', models.BooleanField(default=False)),
                ('time_started', models.DateTimeField(blank=True, null=True)),
                ('time_ended', models.DateTimeField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('marked', models.BooleanField(default=False)),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
                ('duration', models.IntegerField(default=0)),
                ('exam_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userprofile.ExamCenter')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='center.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='CenterSendResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=15)),
                ('timesent', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.CenterResult')),
            ],
        ),
        migrations.CreateModel(
            name='CenterSubjectScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('user', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='CenterUserBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_file', models.FileField(upload_to=b'')),
                ('file_name', models.CharField(max_length=200, unique=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.ExamCenter')),
            ],
        ),
        migrations.CreateModel(
            name='CenterUserScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centeruserquestion', to='bank.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Candidate')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='centercode',
            unique_together=set([('pin', 'srn')]),
        ),
    ]
