# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2020-02-21 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centercode',
            name='buyer',
            field=models.CharField(blank=True, help_text='center name', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='centercode',
            name='set_name',
            field=models.CharField(blank=True, help_text='The name of the batch to issue. This is for easy deactivation', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='centercode',
            name='user',
            field=models.CharField(blank=True, help_text='This is created when pins are issued for sale. This is the login detail', max_length=150, null=True),
        ),
    ]
