# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2021-06-08 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_auto_20200221_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='centerresult',
            name='scripts',
            field=models.TextField(blank=True, null=True),
        ),
    ]
