# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-09 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotline1', models.CharField(max_length=13)),
                ('hotline2', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('email2', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField()),
                ('twitter', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook', models.CharField(blank=True, max_length=50, null=True)),
                ('office', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=10)),
                ('srn', models.CharField(max_length=10)),
                ('used', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('custom', models.BooleanField(default=False)),
                ('custom_center', models.CharField(default='', max_length=1000)),
                ('generated', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.CharField(default='', max_length=30)),
                ('passcode', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Freebie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('pin', models.CharField(max_length=10)),
                ('srn', models.CharField(max_length=10)),
                ('used', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('custom', models.BooleanField(default=False)),
                ('generated', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=10)),
                ('expiration', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guideline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=2)),
                ('text', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('image', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='InBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=1000)),
                ('time_in', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Inboxes',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('state', models.CharField(blank=True, max_length=13, null=True)),
                ('local_govt', models.CharField(blank=True, max_length=13, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=20)),
                ('ip', models.CharField(max_length=40)),
                ('session', models.CharField(max_length=40, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('visit', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Site Views',
            },
        ),
        migrations.CreateModel(
            name='UsedCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('buyer', models.CharField(max_length=30)),
                ('pin', models.CharField(max_length=10)),
                ('serial', models.CharField(max_length=10)),
                ('timeused', models.DateTimeField(auto_now_add=True)),
                ('examination', models.CharField(max_length=20)),
                ('exam_area', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='accesscode',
            unique_together=set([('pin', 'srn')]),
        ),
    ]
