# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-10 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mngr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freebie',
            name='expire',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='freebie',
            name='unlimited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='freebie',
            name='unlimited_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freebie',
            name='uses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='freebie',
            name='user',
            field=models.CharField(default='-', max_length=10),
        ),
    ]
