# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-14 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mngr', '0002_auto_20180110_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('doc', models.FileField(upload_to='files/%Y/%m')),
            ],
        ),
        migrations.DeleteModel(
            name='ImageUpload',
        ),
    ]
