# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-23 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mngr', '0003_auto_20180114_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileuploads',
            options={'verbose_name_plural': 'File Uploads'},
        ),
        migrations.AlterField(
            model_name='accesscode',
            name='buyer',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='accesscode',
            name='custom_center',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='accesscode',
            name='passcode',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
