# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-31 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mngr', '0004_auto_20180123_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscode',
            name='freebie',
            field=models.BooleanField(default=True),
        ),
    ]
