# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-14 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mngr', '0006_invoice_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='transaction_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='transaction_date',
            field=models.DateField(null=True),
        ),
    ]
