# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-26 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mngr', '0009_auto_20181125_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='measure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='practise',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='prepare',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteview',
            name='time_spent',
            field=models.IntegerField(default=0),
        ),
    ]
