# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2020-02-03 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mngr', '0013_auto_20190121_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='caption_image',
            field=models.ImageField(upload_to=b''),
        ),
    ]
