# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2020-02-21 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mngr', '0014_auto_20200203_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='caption_image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
