# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-09 08:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(default=0)),
                ('filled', models.IntegerField(default=0)),
                ('number', models.CharField(max_length=2)),
                ('date', models.DateField(verbose_name='exam date')),
                ('time', models.TimeField(verbose_name='exam time')),
                ('active', models.BooleanField(default=True)),
                ('write_exam', models.BooleanField(default=False)),
                ('show_result', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ExamArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('candidates', models.IntegerField(default=0)),
                ('auto_batch', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('candidates', models.IntegerField(default=0)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('show_photocard', models.BooleanField(default=True)),
                ('check_when', models.DateField(blank=True, null=True)),
                ('cordon', models.BooleanField(default=False)),
                ('exam_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.ExamArea')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Photocard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.IntegerField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.Batch')),
                ('exam_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.ExamArea')),
                ('exam_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.ExamCenter')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('marked', models.BooleanField(default=False)),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Batch')),
                ('exam_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.ExamArea')),
                ('exam_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.ExamCenter')),
            ],
        ),
        migrations.CreateModel(
            name='SendResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=15)),
                ('timesent', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Result')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regnumber', models.CharField(default='-', max_length=10)),
                ('issue', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('noresult', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('user', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=10)),
                ('serial', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('F', 'female'), ('M', 'male'), ('-', '-')], max_length=1)),
                ('phone', models.CharField(max_length=13)),
                ('course', models.CharField(max_length=100)),
                ('passport', models.ImageField(help_text='Maximum of 50kb.(40x30px)', upload_to='passport/%Y/%m')),
                ('regnum', models.CharField(blank=True, max_length=10, null=True)),
                ('pc', models.BooleanField(default=False)),
                ('seat', models.IntegerField(blank=True, null=True)),
                ('online', models.BooleanField(default=False)),
                ('regdate', models.DateTimeField(auto_now_add=True)),
                ('give_sample', models.BooleanField(default=False)),
                ('giftpin', models.CharField(default='', max_length=10)),
                ('giftserial', models.CharField(default='', max_length=10)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.Batch')),
                ('exam_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.ExamArea')),
                ('exam_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.ExamCenter')),
                ('exam_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.State')),
                ('examination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.Examination')),
                ('subject', models.ManyToManyField(to='bank.Subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WriteAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Batch')),
                ('exam_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.ExamCenter')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='specialcase',
            unique_together=set([('regnumber', 'issue')]),
        ),
        migrations.AddField(
            model_name='result',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userprofile.UserProfile'),
        ),
        migrations.AddField(
            model_name='photocard',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.State'),
        ),
        migrations.AddField(
            model_name='photocard',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userprofile.UserProfile'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.UserProfile'),
        ),
        migrations.AddField(
            model_name='examarea',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.State'),
        ),
        migrations.AddField(
            model_name='batch',
            name='exam_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.ExamCenter'),
        ),
    ]
