# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-20 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mngr', '0008_auto_20181120_2246'),
        ('bank', '0001_initial'),
        ('userprofile', '0002_auto_20180114_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(help_text='yyyy-mm-dd')),
                ('amount', models.PositiveIntegerField(help_text='In Naira')),
                ('bank', models.CharField(choices=[('FCMB', 'FCMB'), ('ACCESS', 'ACCESS'), ('STANBIC', 'STANBIC')], max_length=8)),
                ('depositor_name', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(help_text='Or Teller No.', max_length=50)),
                ('payment_mode', models.CharField(choices=[('bank_walk_in', 'bank_walk_in'), ('bank_transfer', 'bank_transfer')], max_length=14)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Referrer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=13, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('ref_code', models.CharField(max_length=5, unique=True)),
                ('regdate', models.DateTimeField(auto_now_add=True)),
                ('account_no', models.CharField(blank=True, max_length=10, null=True, verbose_name='Acount Number')),
                ('bank', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank')),
                ('account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.State')),
            ],
        ),
        migrations.CreateModel(
            name='UserScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userquestion', to='bank.Question')),
            ],
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='photocard',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='photocard',
            name='exam_area',
        ),
        migrations.RemoveField(
            model_name='photocard',
            name='exam_center',
        ),
        migrations.RemoveField(
            model_name='photocard',
            name='state',
        ),
        migrations.RemoveField(
            model_name='photocard',
            name='user',
        ),
        migrations.AddField(
            model_name='result',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='result',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='feedback',
            field=models.ForeignKey(help_text='How did you hear about this mock?', null=True, on_delete=django.db.models.deletion.CASCADE, to='mngr.Advert'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payment_mode',
            field=models.CharField(choices=[('online', 'online'), ('card', 'card'), ('bank', 'bank')], default='card', max_length=8),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='giftpin',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='giftserial',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='ExamSession',
        ),
        migrations.DeleteModel(
            name='Photocard',
        ),
        migrations.AddField(
            model_name='userscript',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.UserProfile'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Referrer'),
        ),
        migrations.AddField(
            model_name='referral',
            name='user_activated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.UserProfile'),
        ),
        migrations.AddField(
            model_name='bankdirect',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userprofile.UserProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='referrer',
            unique_together=set([('full_name', 'phone_number')]),
        ),
        migrations.AlterUniqueTogether(
            name='bankdirect',
            unique_together=set([('transaction_id', 'bank')]),
        ),
    ]
