# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-13 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20181120_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupReferral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False, help_text='has the sup_referrer been paid?')),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='referrer',
            name='referrer_code',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Code Of Referrer'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mails',
            field=models.BooleanField(default=True, verbose_name='Receive Emails?'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='active',
            field=models.BooleanField(default=False, help_text='has the referred candidate paid?', verbose_name='Candidate Paid?'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='paid',
            field=models.BooleanField(default=False, help_text='has the referrer been paid?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='passport',
            field=models.ImageField(help_text='Maximum of 250kb.(50x50px)', upload_to='passport/%Y/%m'),
        ),
        migrations.AddField(
            model_name='supreferral',
            name='referral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Referral'),
        ),
        migrations.AddField(
            model_name='supreferral',
            name='sup_referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Referrer'),
        ),
    ]
