# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2020-02-03 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20190121_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_file', models.FileField(upload_to=b'')),
                ('file_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='exam_period',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='examarea',
            name='exam_period',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='examcenter',
            name='exam_period',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='user_activated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userprofile.UserProfile'),
        ),
        migrations.AlterField(
            model_name='referrer',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userprofile.State'),
        ),
        migrations.AlterField(
            model_name='result',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userprofile.Batch'),
        ),
        migrations.AlterField(
            model_name='result',
            name='exam_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userprofile.ExamArea'),
        ),
        migrations.AlterField(
            model_name='result',
            name='exam_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userprofile.ExamCenter'),
        ),
        migrations.AlterField(
            model_name='supreferral',
            name='sup_referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userprofile.Referrer'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userprofile.Batch'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='exam_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userprofile.ExamArea'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='exam_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userprofile.ExamCenter'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='exam_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userprofile.State'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='examination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.Examination'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='feedback',
            field=models.ForeignKey(help_text='How did you hear about this mock?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mngr.Advert'),
        ),
    ]
