# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2020-02-14 20:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20200203_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='started',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='result',
            name='timelog',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 2, 14, 20, 46, 27, 946728, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='result',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userbank',
            name='file_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
