# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2021-05-17 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20200214_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscript',
            name='choice',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
